version: "3"

services:
  blogpy_postgresql:
    image: postgres
    container_name: blogpy_postgresql 
    volumes: 
      - blogpy_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env 
    ports:
      - "5432:5432"
    networks:
      - blogpy_netwrok

volumes:
  blogpy_postgresql:
    external: true
networks:
  blogpy_netwrok:
    external: true 

