# Generated by Django 3.2.13 on 2022-05-01 12:35

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='files/article_cover/', validators=[blog.models.validate_file_extensions]),
        ),
    ]
