# Generated by Django 3.2.13 on 2022-04-25 08:19

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.FileField(upload_to='files/article_cover/', validators=[blog.models.validate_file_exceptions]),
        ),
    ]
