# Generated by Django 3.2.13 on 2022-04-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='promot',
            field=models.BooleanField(default=False),
        ),
    ]
