# Generated by Django 3.2.13 on 2022-04-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_promot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='promot',
            new_name='promote',
        ),
    ]
